### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Ok, so this Pull requests just contains the two Travis CI files, including a short addition to the readme. If you don't want that, just pull 87999ec. 

You can find the current build here: https://travis-ci.org/MorgWal/winapi

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Oh, to use it, you just need to activate Travis CI as webservice in the github-repo settings and then login to https://travis-ci.org to activate the repository there.

**Comment by Lastique** [comment]
This will be problematic as I don't have the admin rights for the GitHub project. In any case, it'll take time as I need to understand how it works.

**Comment by klemens-morgenstern** [comment]
Oh ok. If you try this yml file you'll get a problem if you use another branch than develop or master. That is because it checks boostorg/boost out with the same branch.

The travis.jam only exists so it can be copied to user-config.jam which has the toolset-config. That could also be integrated into .travis.yml, but I don't think travis.jam will cause a problem.

**Comment by apolukhin** [comment]
There's a recipe on how to enable TravisCI + Coveralls without admin rights: https://svn.boost.org/trac/boost/wiki/TravisCoverals

**Comment by klemens-morgenstern** [comment]
Hey Andrey,

do you now have admin rights? Will this PR be pulled anytime soon, or can I close it?

**Comment by Lastique** [comment]
I don't have the admin rights. Not yet, anyway.

I had some time to look into Travis CI and Appveyor, and I'll probably go with the latter when I have more time. After all, the main target for Boost.WinAPI is Windows and MSVC, which Travis CI do not support.

**Comment by klemens-morgenstern** [comment]
Makes sense, I didn't know appveyor when I created this PR. Though you could still use travis to also build with mingw.

**Comment by klemens-morgenstern** [comment]
Ok, I added an appveyor.yml, but didn't test it, because it's in my organisation. So you could maybe just copy it.

**Pull request closed without merging**
