### PR TITLE
Fix CryptReleaseContext signature for Windows 2000 (#11896)

### PR DESCRIPTION
**Pull request by gjasny**
See [#11896](https://svn.boost.org/trac/boost/ticket/11896).

### CODE REVIEW

**Comment by Lastique** [comment]
The ticket says the problem is specific to VS2012, yet the preprocessor check does not reflect that.

Also, are you using Windows SDK that comes with the compiler?

**Comment by gjasny** [comment]
I does not have anything to do with VS version, just the `_WIN32_WINNT` setting matters. I created the simple test case with VS2013:

```
#define _WIN32_WINNT 0x0500
#include <windows.h>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp> 
```

When I changes the value from Win2000 / 0x0500 to XP / 0x0501 the error vanished. You can see in the Windows SDK that the function signature for `CryptReleaseContext` changes between 2000 and XP. So my patch just reflects that in the Boost winapi header as well.

**Comment by Lastique** [comment]
Should be fixed in https://github.com/boostorg/winapi/commit/d1ce3b2d3ff45f2958c43d0a8d4296995aca053d.

**Comment by gjasny** [comment]
Thank you for taking care. I guess you did not image going down that rabbit hole 👍

**Pull request closed without merging**
