### PR TITLE
added ReadFile

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Hi Andrey,

I just added the ReadFile function, WriteFile was already in. Test passes and it's rather trivial.

Thx,

Klemens

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Also added ERROR_BROKEN_PIPE constant to readfile. I added it there, not in pipes.hpp because it is an error code provided by ReadFile / WriteFile.

**Comment by klemens-morgenstern** [comment]
Alright, I think that's all for this part. I have the environment in seperate header, which are currently in my repository, So that PR should be finished.

**Comment by Lastique** [comment]
I added ReadFile but not ERROR_BROKEN_PIPE. I intend to add error codes in a separate header, but haven't got around to do it.

**Comment by klemens-morgenstern** [comment]
Ok, thanks.

**Pull request closed without merging**
