### PR TITLE
Adding dbghelp

### PR DESCRIPTION
**Pull request by jlodos**

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
@jlodos Is there interest from your side to have this header somewhere outside of boost.dll ?

**Comment by jlodos** [comment]
@klemens-morgenstern  I am not using it, just trying to help. I do think that it belongs to winapi.

**Comment by Lastique** [comment]
First, please, separate the changes for dbghelp from the other changes.

Second, my concern regarding dbghelp is that it seems an optional development library rather than part of Windows API.

**Comment by jlodos** [comment]
I am not sure of the definition of "Windows API". I agree that there are several different APIs distributed together in the Windows SDK. To me any API from the SDK that forces the user to include windows.h could have its place in winapi. Isn´t that its purpose?

**Comment by Lastique** [comment]
It is. But dbghelp.h is not a part of windows .h.

But you're right that it's distributed in Windows SDK. I can see it is also present in MinGW-w64 but not MinGW. So I guess we could add it, with all contents conditioned on `!defined(BOOST_WINAPI_IS_MINGW)`.

Also, I think you closed the other PR by mistake.

**Comment by Lastique** [comment]
I'm closing this PR as it includes some of the changes that were merged and then modified. Please, rebase for the current develop and only include changes needed for dbghelp.

**Pull request closed without merging**
